### ISSUE TITLE
Can't specify @Valid on a Collection in a superclass

### ISSUE THREAD

**Issue by slugmandrew** [ManfredTremmel/gwt-bean-validators#6]
First of all, **thanks so much** for all of your work on this.

I believe I have run into a common problem with using validators in GWT: Issues with @Valid on a member with some kind of inheritance hierarchy.

My own issue relates to validating a class that contains an abstract member. See the following code:

```
public class SupplyDto extends BaseDto
{
    @NotNull(message = "Supply type must be set")
    private SupplyType type;

    @Valid
    private SupplyDetails supplyDetails; // abstract superclass
}
```
#### SupplyDetails has two subclasses, but we want to validate in the superclass:

```
public abstract class SupplyDetails implements Serializable, HasSupplyDetails
{
    @Pattern(regexp = "^(0[0-8]\\d{6}[1-2]\\d{12})$", message = "MPAN is not valid", groups = QuoteChecks.class)
    protected String number;

    @Valid
    protected BillingPeriods billingPeriods = new BillingPeriods(); // contains a collection with validation annotations
}
```

#### Stack trace:

```
[INFO] --- gwt-maven-plugin:1.0-rc-8:compile (default) @ app ---
[INFO] Compiling module com.utilitiessavings.usavappv7.ProjectDev
[INFO] 0    [main] INFO  org.hibernate.validator.internal.util.Version  - HV000001: Hibernate Validator 5.4.1.Final
[INFO]    Computing all possible rebind results for 'com.utilitiessavings.usavappv7.client.security.ValidationFactory.GwtValidator'
[INFO]       Rebinding com.utilitiessavings.usavappv7.client.security.ValidationFactory.GwtValidator
[INFO]          Invoking generator de.knightsoftnet.validators.rebind.ValidatorGenerator
[INFO]             [ERROR] Generator 'de.knightsoftnet.validators.rebind.ValidatorGenerator' threw an exception while rebinding 'com.utilitiessavings.usavappv7.client.security.ValidationFactory.GwtValidator'
[INFO] java.lang.NullPointerException
[INFO] 	at de.knightsoftnet.validators.rebind.BeanHelper.getAssociationType(BeanHelper.java:78)
[INFO] 	at de.knightsoftnet.validators.rebind.BeanHelperCache.doCreateHelperForProp(BeanHelperCache.java:140)
[INFO] 	at de.knightsoftnet.validators.rebind.BeanHelperCache.doCreateHelper(BeanHelperCache.java:124)
[INFO] 	at de.knightsoftnet.validators.rebind.BeanHelperCache.createHelper(BeanHelperCache.java:71)
[INFO] 	at de.knightsoftnet.validators.rebind.BeanHelperCache.doCreateHelperForProp(BeanHelperCache.java:151)
[INFO] 	at de.knightsoftnet.validators.rebind.BeanHelperCache.doCreateHelper(BeanHelperCache.java:124)
[INFO] 	at de.knightsoftnet.validators.rebind.BeanHelperCache.createHelper(BeanHelperCache.java:71)
[INFO] 	at de.knightsoftnet.validators.rebind.AbstractCreator.createBeanHelper(AbstractCreator.java:80)
[INFO] 	at de.knightsoftnet.validators.rebind.ValidatorCreator.<init>(ValidatorCreator.java:69)
[INFO] 	at de.knightsoftnet.validators.rebind.ValidatorGenerator.generateGenericValidator(ValidatorGenerator.java:123)
[INFO] 	at de.knightsoftnet.validators.rebind.ValidatorGenerator.generate(ValidatorGenerator.java:73)
[INFO] 	at com.google.gwt.core.ext.IncrementalGenerator.generateNonIncrementally(IncrementalGenerator.java:40)
[INFO] 	at com.google.gwt.dev.javac.StandardGeneratorContext.runGeneratorIncrementally(StandardGeneratorContext.java:745)
[INFO] 	at com.google.gwt.dev.cfg.RuleGenerateWith.realize(RuleGenerateWith.java:103)
[INFO] 	at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.rebind(StandardRebindOracle.java:78)
[INFO] 	at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:262)
[INFO] 	at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:251)
[INFO] 	at com.google.gwt.dev.PrecompilationContextCreator$1.getAllPossibleRebindAnswers(PrecompilationContextCreator.java:86)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createStaticRebindExpression(UnifyAst.java:519)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createRebindExpression(UnifyAst.java:487)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.maybeHandleMagicMethodCall(UnifyAst.java:415)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.visit(UnifyAst.java:402)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:265)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
[INFO] 	at com.google.gwt.dev.jjs.ast.JCastOperation.traverse(JCastOperation.java:76)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
[INFO] 	at com.google.gwt.dev.jjs.ast.JReturnStatement.traverse(JReturnStatement.java:40)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor$ListContext.traverse(JModVisitor.java:88)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemove(JModVisitor.java:331)
[INFO] 	at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:94)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:139)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:135)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:83)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:786)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:778)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst.mainLoop(UnifyAst.java:1401)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst.exec(UnifyAst.java:896)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.unifyJavaAst(JavaToJavaScriptCompiler.java:1410)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.constructJavaAst(JavaToJavaScriptCompiler.java:1222)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:1140)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:255)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:255)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:204)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:155)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:144)
[INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:118)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
[INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:125)
[INFO]    [ERROR] Errors in 'com/utilitiessavings/usavappv7/client/security/ValidationFactory.java'
[INFO]       [ERROR] Line 57: Failed to resolve 'com.utilitiessavings.usavappv7.client.security.ValidationFactory.GwtValidator' via deferred binding
```

This has been logged as an issue a few separate times, and each may provide some more information so I'll link to them here:

1. https://github.com/gwtproject/gwt/issues/8516
2. https://github.com/gwtproject/gwt/issues/7263
3. https://github.com/gwtproject/gwt/issues/8816

Is this something that can be fixed, or do you see it as being a long term limitation of GWT? It would be great if this could be fixed at some point.

Hope that helps!

**Comment by ManfredTremmel** [comment]
Sorry for answering so late, the notification mail was sorted into my spam folder. I'll try to find a solution for this problem tomorrow.

**Comment by ManfredTremmel** [comment]
@slugmandrew, can you try again with version 0.44.4, which I've uploaded now, it should fix the problem.

**Comment by slugmandrew** [comment]
Thanks for this, and no worries about the slow reply! I'll have a proper test of this functionality this week and get back to you.

Cheers!

**Comment by slugmandrew** [comment]
I tried the updated version, but I was still getting a NPE when creating the interface for SupplyDetailsValidator.

I found a workaround though (at least for me). The issue wasn't that `BillingPeriods` contained a `List<T>` annotated with `@Valid`, but that `BillingPeriods` implemented the `Iterable<T>` interface. Once I removed that (it's just a wrapper for a `List<BillingPeriod>` anyway).

It compiles now and seems to validate nicely, but it also works with the old version, so not sure if your changes had any effect.

Let me know if there's anything else I can do to help.

_**Sidebar:** Should this library work with SuperDevMode and reconfigure any annotation changes on recompile? When I recompile I can take an annotation away, but no changes or additions are ever picked up. Are you possibly caching too much or am I doing something wrong?_

Cheers!!

**Comment by ManfredTremmel** [comment]
Can you provide me the classes and Interfaces which cause the problem in a way I should be able to compile them and reproduce the problem? I've included the classes from https://github.com/gwtproject/gwt/issues/7263 as testcases and they work. So we do have another problem in your case.

_**Sidebar:** I don't cache something, but there's a lot of code generated by code generators. I'm not expert in the incremental compile process which is used in SuperDevMode and what exactly triggers the rebuild. Sometimes I do have some not reproduceable problems, deleting entries in tmp directory and gwt-unitCache of the project solves it normaly._

**Comment by ManfredTremmel** [comment]
@slugmandrew  anything for me? Need something to reproduce the bug. Your SupplyDto and SupplyDetails are missing BaseDto, SupplyType, HasSupplyDetails and BillingPeriods.

**Comment by slugmandrew** [comment]
@ManfredTremmel Apologies. I have been really busy migrating my entire data layer from app engine datastore to postgresql, and then the last week I have been recovering from an operation.

Back to full strength today though so I'll get a small demo project set up and deploy it for you that hopefull reproduces the issue.

**Comment by slugmandrew** [comment]
@ManfredTremmel Sorry dude, I had some serious technical issues that I had to deal with today. I'll get that demo project to you tomorrow.

**Comment by ManfredTremmel** [comment]
@slugmandrew thanks a lot, I hope I can fix the problem soon, when I can reproduce it.

**Comment by ManfredTremmel** [comment]
@slugmandrew I haven't heard something from you, still interested to solve the problem?

**Comment by ManfredTremmel** [comment]
Closed because of inactivity!
Waited nearly four month for the example project to reproduce the bug. Please open a new bug, if you can give me something to reproduce the situation.
