### ISSUE TITLE
Unable to compile a GWT project if gwt-bean-validators is included

### ISSUE THREAD

**Issue by oloftus** [ManfredTremmel/gwt-bean-validators#8]
Following the steps given [here](https://github.com/ManfredTremmel/gwt-bean-validators), I am not able to compile a GWT project if gwt-bean-validators is included because of the compile error given below.

Rather than repeat myself here, the attached project is the bare minimum needed to trigger the errors.

- **[gwt-test.zip](https://github.com/ManfredTremmel/gwt-bean-validators/files/1537083/gwt-test.zip)**

To execute the code, extract the zip, `cd` to the extracted directory and run `./gradlew gwtc` to run the GWT Compiler.

I am aware of [Issue#6](https://github.com/ManfredTremmel/gwt-bean-validators/issues/6) which has the same stracktrace but appears to describe a different problem that triggers it.

Finally, thank you for this project!

```
Compiling module gwtvalidatortest.module
   Resolving gwtvalidatortest.client.GwtValidatorFactory.GwtValidator
      Found type 'gwtvalidatortest.client.GwtValidatorFactory.GwtValidator'
         Resolving annotation for de.knightsoftnet.validators.client.GwtValidation
            [WARN] Annotation error: cannot resolve gwtvalidatortest.client.Entity
            [ERROR] Annotation error: expected class java.lang.Class, got null
   Resolving gwtvalidatortest.client.ReflectGetterFactory.GwtGetReflector
      Found type 'gwtvalidatortest.client.ReflectGetterFactory.GwtGetReflector'
         Resolving annotation for de.knightsoftnet.validators.client.GwtValidation
            [WARN] Annotation error: cannot resolve gwtvalidatortest.client.Entity
            [ERROR] Annotation error: expected class java.lang.Class, got null
0    [main] INFO  org.hibernate.validator.internal.util.Version  - HV000001: Hibernate Validator 5.4.2.Final
   Computing all possible rebind results for 'gwtvalidatortest.client.GwtValidatorFactory.GwtValidator'
      Rebinding gwtvalidatortest.client.GwtValidatorFactory.GwtValidator
         Invoking generator de.knightsoftnet.validators.rebind.ValidatorGenerator
            [ERROR] Generator 'de.knightsoftnet.validators.rebind.ValidatorGenerator' threw an exception while rebinding 'gwtvalidatortest.client.GwtValidatorFactory.GwtValidator'
java.lang.NullPointerException
        at de.knightsoftnet.validators.rebind.BeanHelperCache.createHelper(BeanHelperCache.java:70)
        at de.knightsoftnet.validators.rebind.AbstractCreator.createBeanHelper(AbstractCreator.java:80)
        at de.knightsoftnet.validators.rebind.ValidatorCreator.<init>(ValidatorCreator.java:69)
        at de.knightsoftnet.validators.rebind.ValidatorGenerator.generateGenericValidator(ValidatorGenerator.java:123)
        at de.knightsoftnet.validators.rebind.ValidatorGenerator.generate(ValidatorGenerator.java:73)
        at com.google.gwt.core.ext.IncrementalGenerator.generateNonIncrementally(IncrementalGenerator.java:40)
        at com.google.gwt.dev.javac.StandardGeneratorContext.runGeneratorIncrementally(StandardGeneratorContext.java:745)
        at com.google.gwt.dev.cfg.RuleGenerateWith.realize(RuleGenerateWith.java:103)
        at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.rebind(StandardRebindOracle.java:78)
        at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:262)
        at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:251)
        at com.google.gwt.dev.PrecompilationContextCreator$1.getAllPossibleRebindAnswers(PrecompilationContextCreator.java:86)
        at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createStaticRebindExpression(UnifyAst.java:519)
        at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createRebindExpression(UnifyAst.java:487)
        at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.maybeHandleMagicMethodCall(UnifyAst.java:415)
        at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.visit(UnifyAst.java:402)
        at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:265)
        at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
        at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
        at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
        at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
        at com.google.gwt.dev.jjs.ast.JCastOperation.traverse(JCastOperation.java:76)
        at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
        at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
        at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
        at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
        at com.google.gwt.dev.jjs.ast.JReturnStatement.traverse(JReturnStatement.java:40)
        at com.google.gwt.dev.jjs.ast.JModVisitor$ListContext.traverse(JModVisitor.java:88)
        at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemove(JModVisitor.java:331)
        at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:94)
        at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
        at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
        at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:139)
        at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:135)
        at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:83)
        at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
        at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
        at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
        at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:786)
        at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:778)
        at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
        at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
        at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
        at com.google.gwt.dev.jjs.impl.UnifyAst.mainLoop(UnifyAst.java:1401)
        at com.google.gwt.dev.jjs.impl.UnifyAst.exec(UnifyAst.java:896)
        at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.unifyJavaAst(JavaToJavaScriptCompiler.java:1410)
        at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.constructJavaAst(JavaToJavaScriptCompiler.java:1222)
        at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:1140)
        at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:255)
        at com.google.gwt.dev.Precompile.precompile(Precompile.java:255)
        at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
        at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
        at com.google.gwt.dev.Compiler.compile(Compiler.java:204)
        at com.google.gwt.dev.Compiler.compile(Compiler.java:155)
        at com.google.gwt.dev.Compiler.compile(Compiler.java:144)
        at com.google.gwt.dev.Compiler$1.run(Compiler.java:118)
        at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
        at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
        at com.google.gwt.dev.Compiler.main(Compiler.java:125)
   [ERROR] Errors in 'gwtvalidatortest/client/GwtValidatorFactory.java'

**Comment by ManfredTremmel** [comment]
Thanks @oloftus for providing the test project. I'll try to fix this ASAP

**Comment by ManfredTremmel** [comment]
Hello @oloftus , your situation is different and also the stacktrace is different, the `[ERROR] Annotation error: expected class java.lang.Class, got null` shows me, the entity couldn't be found in the annotation.
I'm not a gradle expert, but this build.gradle file works fine with the rest of your project copy it into the project and run `./gradlew clean build`, gwt build is done:

```
group "gwtvalidatortest"
version "1.0-SNAPSHOT"

def gwtModuleName = "gwtvalidatortest.module"

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'de.richsource.gradle.plugins:gwt-gradle-plugin:0.6'
    }
}

apply plugin: "war"
apply plugin: "gwt"

repositories {
    mavenCentral()
}
dependencies {
    providedCompile("javax.validation:validation-api:1.1.0.Final")
    providedCompile("javax.validation:validation-api:1.1.0.Final:sources")
    providedCompile("de.knightsoft-net:gwt-bean-validators:0.45.0")
}

gwt {
    gwtVersion="2.8.2"
    minHeapSize = "512M"
    maxHeapSize = "1024M"
    modules "gwtvalidatortest.module"
    project.webAppDirName = "webapp"
}

```

**Comment by oloftus** [comment]
Thank you for taking a look and my apologies that it turned out to be my own error
